<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Microsoft.FlightSimulator.SimConnect</AssemblyName>
    <RootNamespace>Microsoft.FlightSimulator.SimConnect</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
